name: Testing xml_grep

on:
  workflow_dispatch

jobs:
  print_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Install mvn
        run: sudo apt-get install -y maven
      - name: Set variables
        run: |
          VER=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VER" >> $GITHUB_ENV
      - name: "Print value from env variable"
        run: echo "Version is $version"
