name: Create release

on:
  workflow_dispatch

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Install maven
        run: sudo apt-get install -y maven
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21
      - name: Set variables
        run: |
          VER=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
          NAME=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.name -q -DforceStdout)
          echo "plugin_jar=$NAME-$VER.jar" >> $GITHUB_ENV
      - name: Build plugin jar
        run: mvn package
      - name: Create github release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        uses: softprops/action-gh-release@v2.0.5
        with:
          files: target/{{ env.plugin_version }
